### ISSUE TITLE
Unexpected error during call_plugin_service

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#107]
HI,
Now I've got logging working, I can see not everything is 100% happy. Unsure if this is related to a configuration issue on my platform or PV_opt.

08:19:12 INFO AppDaemon: App initialization complete
08:20:55 WARNING AppDaemon: Excessive time spent in callback 'optimise_time() in pv_opt', Thread 'thread.thread-0' - now complete after 55.622581 seconds (limit=45.0)
09:51:01 WARNING AppDaemon: Excessive time spent in callback 'optimise_time() in pv_opt', Thread 'thread.thread-0' - now complete after 61.729314 seconds (limit=45.0)
10:01:00 WARNING AppDaemon: Excessive time spent in callback 'optimise_time() in pv_opt', Thread 'thread.thread-0' - now complete after 60.701613 seconds (limit=45.0)
10:10:59 WARNING AppDaemon: Excessive time spent in callback 'optimise_time() in pv_opt', Thread 'thread.thread-0' - now complete after 59.672076 seconds (limit=45.0)
10:21:00 WARNING AppDaemon: Excessive time spent in callback 'optimise_time() in pv_opt', Thread 'thread.thread-0' - now complete after 60.980362 seconds (limit=45.0)
10:30:13 ERROR HASS: ------------------------------------------------------------
10:30:13 ERROR HASS: Unexpected error during call_plugin_service()
10:30:13 ERROR HASS: Service: default.number.set_value Arguments: {'entity_id': 'number.solis_backup_mode_soc', 'value': 41}
10:30:13 ERROR HASS: ------------------------------------------------------------
10:30:13 ERROR HASS: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py", line 543, in call_plugin_service
    self.update_perf(bytes_sent=len(json.dumps(data)), bytes_recv=len(await r.text()), requests_sent=1)
                                    ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable

10:30:13 ERROR HASS: ------------------------------------------------------------
10:31:02 WARNING AppDaemon: Excessive time spent in callback 'optimise_time() in pv_opt', Thread 'thread.thread-0' - now complete after 62.177296 seconds (limit=45.0)
10:38:27 WARNING AppDaemon: Excessive time spent in utility loop: 2902.0ms, 3.0ms in check_app_updates(), 2899.0ms in other
10:40:13 ERROR HASS: ------------------------------------------------------------
10:40:13 ERROR HASS: Unexpected error during call_plugin_service()
10:40:13 ERROR HASS: Service: default.number.set_value Arguments: {'entity_id': 'number.solis_backup_mode_soc', 'value': 40}

[pv_opt.log](https://github.com/fboundy/pv_opt/files/14182513/pv_opt.log)

[Uploading main.log…]()

Nothing in error.log. 

Thanks.

**Comment by fboundy** [comment]
I think this is happening because the inverter will only allow you to set the Backup SOC when the inverter is in Backup/Reserve mode. I suspect it needs to wait for a second between the commands. Should be addressed in #107

**Comment by fboundy** [comment]
Closing as I believe this is fixed in 3.8.x. Please re-open if needed.
