### ISSUE TITLE
Something wrong with the release 3.7.2

### ISSUE THREAD

**Issue by SzosszeNET** [stevebuk1/pv_opt#111]
Just installed 3.7.2 but it still says it's 3.6.2

If you download the source file https://github.com/fboundy/pv_opt/releases/tag/3.7.2 you'll find 3.6.2 files in the zip

**Comment by SzosszeNET** [comment]
https://github.com/fboundy/pv_opt/tree/3.7.2 is also still 3.6.2

**Comment by fboundy** [comment]
Should be fixed now
