### ISSUE TITLE
Trying to set inverter current value higher than threshold

### ISSUE THREAD

**Issue by ThomasPrior** [stevebuk1/pv_opt#128]
**Describe the bug**
PV_OPT keeps trying to set my inverter import/export current above the 100A limit of my inverter.

**Expected behavior**
I would expect PV_OPT to either retrieve the maximum value from the inverter or the config file and ensure that the value passed for export does not exceed that value.

**Screenshots**
![image](https://github.com/fboundy/pv_opt/assets/34111848/49150016-ade8-48f8-b89a-4c8c0de3e102)
![image](https://github.com/fboundy/pv_opt/assets/34111848/c6e869db-3f75-475b-9f53-0990b915e3ae)

**Additional context**
pv_opt.log attached
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14323828/pv_opt.log)

HA version:
Core 2024.2.2
Frontend 20240207.1

PV_Opt version:
3.8.9

**Comment by fboundy** [comment]
Closing this issue as it is the same as #91

**Comment by fboundy** [comment]
It looks like this is at least partially because the discharge power is being rounded up from 4840w to 5000w. In 3.8.10 try setting the Power Resolution to 0 (it will probably cause a divide by zero error in previous versions) and let me know if that helps.  The trouble with the Charge Current Limit is that it is set dynamically by the BMS.

**Comment by ThomasPrior** [comment]
I'm afraid this is still happening. 

My next charge is calculated at 102A, which cannot be written to the inverter as the limit is 100A.

Can a limit be set that caps the optimum charge current value?

![Screenshot_20240406-222356_Home_Assistant.jpg](https://github.com/fboundy/pv_opt/assets/34111848/631e5bf3-eae5-459d-8260-fb0bcc51d57b)

![Screenshot_20240406-222204_Home_Assistant.jpg](https://github.com/fboundy/pv_opt/assets/34111848/32320de4-5424-4d60-b8c3-a21372a15759)

![Screenshot_20240406-222208_Home_Assistant.jpg](https://github.com/fboundy/pv_opt/assets/34111848/8e426880-f58d-44e5-a3e3-77d3d535587c)
