### ISSUE TITLE
AppDaemon log entries regarding deprecation of 'T' for pv_opt integration

### ISSUE THREAD

**Issue by pepetheprawn** [stevebuk1/pv_opt#137]
Hi, 

I've just got PV_Opt working (I think) and everything is looking great. I just checked my AppDaemon logs to be sure and had loads of entries like this:

/homeassistant/appdaemon/apps/pv_opt/pvpy.py:247: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead

[AppDaemon_Log.txt](https://github.com/fboundy/pv_opt/files/14393606/AppDaemon_Log.txt)

Thanks for your great work.

**Comment by fboundy** [comment]
I’ve fixed this in the Dev branch so should be sorted in the next release.

**Comment by fboundy** [comment]
Now fixed by #138
