### ISSUE TITLE
pv_opt fails to complete if export tariff not provided

### ISSUE THREAD

**Issue by stevebuk1** [stevebuk1/pv_opt#140]
My import tariff is Octopus Intelligent Go but I have no export tariff as my install is DIY with no MCS.

If an export tariff is not provided PvOptimiser does not complete and generates various errors in the error log. The Pv Opt status remains in "Loading Tariffs". 

The issue prevails for all of the following cases/options (although the error logs are slightly different):
1) Using the bottlecapdave Octopus Energy Integration (octopus_auto: True)
2) Using the Octopus API directly  (Octopus_auto: False and providing Octopus account and API key in config.yaml)
3) Disabling octopus_auto and not providing account/key, and setting import tariff directly in config.yaml("octopus_import_tariff_code: E-1R-INTELLI-BB-VAR-23-03-01-N").  but with no export tariff set. 

Option 3 should allow the issue to be repeated regardless of actual tariff use. 

Setting a manual SEG tariff in Config.yaml clears the issue ("octopus_export_tariff_code: E-1R-OUTGOING-SEG-FIX-12M-BB-23-02-09-G") but I'm unsure whether an export tariff of 4.1p produces the same result of an export tariff of 0p, even if discharging is disabled. 

I've raised this as a bug rather than a feature request due to the exceptions raised, but the request is either that the code handles the lack of export tariff and defaults to 0p export, or a switch is provided to switch off export tariff searching/loading completely and default to 0p. 

error.log and appdaemon.log excerpts attached for Option3. 

#
[appdaemon.log](https://github.com/fboundy/pv_opt/files/14396545/appdaemon.log)
[error.log](https://github.com/fboundy/pv_opt/files/14396546/error.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14396547/pv_opt.log)

**Comment by stevebuk1** [comment]
Adding Appdaemon.log due to attachment error above. 

[appdaemon.log](https://github.com/fboundy/pv_opt/files/14396532/appdaemon.log)

**Comment by fboundy** [comment]
This is v3.8.10 by the look of it. Can you please re-try with 3.9.3?

Thanks

**Comment by stevebuk1** [comment]
3.9.3 downloaded, Pv-opt entity export prices all now showing 0p - thanks!!
