### ISSUE TITLE
Solcast Profiles Day Forecast Totals

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#145]
Would it be possible to display the predicted solar forecast for today & tomorrow separately for the 3x different Solcast profiles?

I know the data is there already but unsure how to do this.

Thanks!

**Comment by lazy-pete** [comment]
I changed the colours in the dashboard to make it clearer which was which -
that helped.

P

**Comment by fboundy** [comment]
Your can do this with a template sensor:

    {% set ns = namespace(x='pv_estimate10', y=0)%}
    {% set l = state_attr('sensor.solcast_pv_forecast_forecast_tomorrow', 'detailedForecast') %}
    {% for e in l %}
      {%set ns.y = ns.y+ e[ns.x]/2%}
    {%endfor%}
    {{ns.y}}
