### ISSUE TITLE
Saving Sessions

### ISSUE THREAD

**Issue by stjohncanning** [stevebuk1/pv_opt#147]
Enjoying the functions of this excellent program.  Would it be possible to have an option to enter all the saving sessions but NOT activate the 'discharge' option for background day-to-day discharging?   
Reason is to avoid cycling the batteries for the (normally marginal) day to day savings, but do want to take advantage of the saving sessions which pay significantly better.   
Currently have to change the settings ('discharge' and 'cycle') in advance of the session, and reset afterwards.  A switch to enter or not enter saving sessions, which then dealt with the discharge and cycling for all future sessions, would be good.  
Obviously would have to be activated in advance of each session to set up the charging schedule, probably when the saving session was announced, and cancelled after that session.

**Comment by fboundy** [comment]
Yes - that should be do-able

**Comment by fboundy** [comment]
Rather than set this as a switch I have added a separate theshold for discharging: `number.pvopt_discharge_threshold_p`. You should be able to set this at an appropriate level than only saver sessions are included. It should also work for the situation where a lot of PV generated charge is worth dumping at the end of the day.

**Comment by stjohncanning** [comment]
That's a much better more generic solution than my proposal - thanks!
Do you have a 'buy me a beer' link anywhere?

**Comment by fboundy** [comment]
I don’t but maybe I’ll set one up…

**Comment by lazy-pete** [comment]
Good idea !

**Comment by stjohncanning** [comment]
donation made to Mountain Rescue team - great idea.
