### ISSUE TITLE
Support for GivEnergy Inverters

### ISSUE THREAD

**Issue by DrJohnM61** [stevebuk1/pv_opt#154]
**Is your feature request related to a problem? Please describe.**
We do not have solar (low priority as East/West roof and high latitudes in Scotland providing limited benefit in the winter months and poor ROI), but we do have a givenergy all-in-one battery/inverter. This integration looks to be perfect for scheduling charge and discharge cycles based on the Octopus Agile tariff.

**Describe the solution you'd like**
An ability to configure without solar, ie, just charging and discharging using grid supply.

**Describe alternatives you've considered**

**Additional context**

**Comment by fboundy** [comment]
That should be possible. It will also require a GivEnergy inverter controller to be written

**Comment by DrJohnM61** [comment]
Thank you for the quick response and consideration.

As a fyi, there is the GivTCP integration that exposes all of the givenergy inverter information/controls (https://github.com/britkat1980/giv_tcp)

**Comment by fboundy** [comment]
Do you use the Rest API or MQTT with GivTCP?

**Comment by DrJohnM61** [comment]
MQTT.

I just followed the process as written in this tutorial https://www.speaktothegeek.co.uk/2022/12/givtcp-v2-givenergy-and-home-assistant-with-solar-forecast-automation/#overview

**Comment by fboundy** [comment]
OK - I will have a look at that. The option to have no solar will be in the next release (3.12.0) so you should be able to configure your setup in read-only mode using the parameters in `config.yaml`. Just leave the inverter type as `solis` for now. Once you have it running read-only we can look at getting the inverter controller plug-in built.

**Comment by DrJohnM61** [comment]
Thank you. I will take a look when I am back from Canada.

**Comment by fboundy** [comment]
OK let me know when you've had a chance to look at it

**Comment by philicibine** [comment]
Sorry to bring up a stale issue here, but I have a friend that will soon be getting this inverter / battery setup.  Will be glad to help with getting it setup for this.  Hopefully you have time?
