### ISSUE TITLE
HASS log - recorder issue - Content length

### ISSUE THREAD

**Issue by swests** [stevebuk1/pv_opt#159]
**Describe the bug**
Warning in log from recorder - attribute length for some entiries greater than 16k and not being recorded.

**To Reproduce**
Check the HA log

**Expected behavior**
Content to be recorded (perhaps in segment) 

**Screenshots**
<img width="1124" alt="image" src="https://github.com/fboundy/pv_opt/assets/5365747/c55e3f96-b0de-4b22-8588-954a9ddd989b">

**Desktop (please complete the following information):**
HA latest and pv_opt latest

**Additional context**
Message in HA log:

```
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:584
Integration: Recorder (documentation, issues)
First occurred: 09:51:46 (4 occurrences)
Last logged: 12:05:05

State attributes for sensor.pvopt_base_cost exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for sensor.pvopt_opt_cost exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

**Comment by fboundy** [comment]
You probably don’t need this saved to the database so I don’t see it as a major issue. I’m not seeing this myself but that may be because I use MariaDB and InfluxDB rather than the default database.

**Comment by swests** [comment]
I’m also using the same DB combo. 

Ok will ignore for now.

**Comment by fboundy** [comment]
That’s interesting. I’ll check my logs then as I’ve not seen this one but the attributes aren’t needed for posterity.

**Comment by swests** [comment]
Just looking to understand this a little more.  Checking the attributes, sensor.pvopt_opt_cost_current is holding 'period start' dates from 2024-03-22.  Am I ok to clear out the soc, forced, import, export, grid, and solar data.  Taken today 25th March.  seems it's last updated 23rd March.

![image](https://github.com/fboundy/pv_opt/assets/5365747/71025bbb-4600-4687-a377-91b016ecb17c)

**Comment by fboundy** [comment]
Do you have entries under the `alt_tariffs` section in your `config.yaml` file? If so I suggest you comment out or delete them and then all the `sensor.pvopt_opt_cost_*` entities will be redundant (except for `sensor.pvopt_opt_cost`). If you restart HA and AppDaemon they should then disappear.
