### ISSUE TITLE
Entity not picking up after restart number.solis_battery_minimum_soc

### ISSUE THREAD

**Issue by lazy-pete** [stevebuk1/pv_opt#177]
**Describe the bug**

updated Pv_opt to most recent version via HACS. 
still noting that following reboot I get a dashboard error regarding failure to detect number.solis_battery_minimum_soc. 

This entity is present and visible in entities with a number present via slider. 

Also still seeing different setting in dashboard from config.yaml despite ‘overwrite on restart’ set to True. 

RTC sync error also persists. 

**To Reproduce**

Restart HA 

**Expected behavior**
Restart retains config.yaml settings in dashboard, and allows pv_opt to run by detecting all required entities. 

**Screenshots**

![IMG_6157](https://github.com/fboundy/pv_opt/assets/30950467/d59f0b3c-8e7b-42a2-b527-6b74c7b04982)
![IMG_6158](https://github.com/fboundy/pv_opt/assets/30950467/e165d3e9-46f2-418b-bf77-5dbde2aea443)
![IMG_6159](https://github.com/fboundy/pv_opt/assets/30950467/7605b13d-ceb8-41cf-a4bd-1c2bccf67fd8)
![IMG_6160](https://github.com/fboundy/pv_opt/assets/30950467/eac31d2d-66dc-477c-96c5-af78d20b3fa8)
![IMG_6161](https://github.com/fboundy/pv_opt/assets/30950467/9ff264ad-22cf-4e75-adcf-1552abc39514)
![IMG_6162](https://github.com/fboundy/pv_opt/assets/30950467/39345c96-a195-45b1-a600-6b7b1d7ab4c2)
![IMG_6163](https://github.com/fboundy/pv_opt/assets/30950467/ee67b1c2-c21c-48f2-aec3-7e77207aa5de)
![IMG_6164](https://github.com/fboundy/pv_opt/assets/30950467/961927fd-ae0a-4459-81e5-39e075774fe7)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lazy-pete** [comment]
[error.log](https://github.com/fboundy/pv_opt/files/14748229/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/14748230/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14748231/pv_opt.log)

**Comment by fboundy** [comment]
Ah - that release was a pre-Release. I tagged it wrong. Please revert to 3.12.1

What versions of the Solax integration and Home Assistant Core are you running?

It also looks to me like the Solax integration hadn't properly started when you restarted AppDaemon. All the `solis` entites are showing 0 or `unknown` at 18:29:11.

**Comment by lazy-pete** [comment]
Ok - not quite sure I know how to revert ! Shall Google. 

Most recent versions of HAOSS / core / Solax etc (no updates available. 

Will await Solax boot and try again.

**Comment by lazy-pete** [comment]
Actually just after that I found there was another Solax update with your rtc_sync fix. Installed now and seems to have sorted that error. 

Also re downloaded 3.12.1 and things seemed fine after I restarted AppDaemon. 

[error.log](https://github.com/fboundy/pv_opt/files/14748515/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/14748517/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14748518/pv_opt.log)

**Comment by lazy-pete** [comment]
Sent a couple of beers to the MRT - excellent cause. Not needed them yet myself, but you never know when it’s going to go wrong back there !
