### ISSUE TITLE
PV Opt generating negative discharge windows that don't match end time shown in UI

### ISSUE THREAD

**Issue by ThomasPrior** [stevebuk1/pv_opt#198]
**Describe the bug**
Since the DST change I've seen a few odd charging windows.

pv_opt log output shows:

17:08:08 INFO: end : 04-Apr 17:00 BST
--
17:08:08 INFO: start : 04-Apr 17:07 BST

This is displayed in HomeAssistant as finishing an hour later:

![image](https://github.com/fboundy/pv_opt/assets/34111848/485167f0-13bf-4f61-93ca-adf1c22dd8bb)

The inverter receives the end time of 17:00 instead of the expected 18:00, making the discharge window -8 minutes.

![Screenshot_20240404-171206_SolisCloud](https://github.com/fboundy/pv_opt/assets/34111848/d865a77d-7eaa-4911-83ff-1b9e22481612)

Time on inverter seems to be set correctly.

![Screenshot_20240404-171319_SolisCloud](https://github.com/fboundy/pv_opt/assets/34111848/dfd4ce30-35bf-4bd1-a122-c1f60af6efdb)

[pv_opt.log](https://github.com/fboundy/pv_opt/files/14874079/pv_opt.log)

**Comment by ThomasPrior** [comment]
Adding second log with the same behaviour. 

As shown in HomeAssistant:
Start 17:20
End: 18:00

As shown in logs and on inverter:
Start: 17:20
End: 17:00

[pv_opt.log](https://github.com/fboundy/pv_opt/files/14874148/pv_opt.log)

**Comment by jacekowski** [comment]
It could be the same thing i'm seeing in #197

**Comment by ThomasPrior** [comment]
Interesting, I saw what I thought to be a very poor plan for today (discharge everything, all day) and that's what led me to finding this. 

Also on fixed 15p/kWh of export.

**Comment by fboundy** [comment]
This should be fixed in 3.14.0. There's a beta version out now if you want to test it. Best wait for beta-4 actually. Fixes another couple of bugs.

**Comment by fboundy** [comment]
> It could be the same thing I'm seeing in #197

Not sure these are the same. There is a "time zone" issue which I think I've fixed but I think at least part of what is happening in #197 is that there is a cost benefit to forced discharging but it's not intuitive.

**Comment by ThomasPrior** [comment]
Thank you again for your prompt attention on this and previous issues.
