### ISSUE TITLE
Modify battery capacity in pc_opt.py for users with larger battery capacity than 20kWh

### ISSUE THREAD

**Issue by spetrie13** [stevebuk1/pv_opt#206]
Increase battery capacity in pv_opt-py for users with battery capacity larger than 20kWh. (I have 25kWh so slider does not cater for my case.)

Original:
"battery_capacity_wh": {
        "default": 10000,
        "domain": "number",
        "attributes": {
            "min": 2000,
            "max": 20000,
            "step": 100,
            "unit_of_measurement": "Wh",
            "device_class": "energy",
            "mode": "slider",
        },

To say

    "battery_capacity_wh": {
        "default": 10000,
        "domain": "number",
        "attributes": {
            "min": 2000,
            "max": 30000,
            "step": 100,
            "unit_of_measurement": "Wh",
            "device_class": "energy",
            "mode": "slider",
        },

**Comment by fboundy** [comment]
Should be done in 3.14.1
