### ISSUE TITLE
Manual tariff setting

### ISSUE THREAD

**Issue by spetrie13** [stevebuk1/pv_opt#211]
Add a section in config file to manually specify tariff rates for both import and export and disable the octopus energy rate aquisition.

This will be usefully when moving away from octopus to another energy provider and still be able to use pv opt.

Thanks.

**Comment by fboundy** [comment]
Yes - it's been something I've been planning. Will try to add it to 3.15

**Comment by fboundy** [comment]
Bump

**Comment by augard** [comment]
Can we reopen, it will be really useful :(

**Comment by spetrie13** [comment]
Agreed, now moved away from Octopus so can't use the automation with new
tariff.

**Comment by fboundy** [comment]
Added in 3.17.0
