### ISSUE TITLE
Incorrect release label?

### ISSUE THREAD

**Issue by ThomasPrior** [stevebuk1/pv_opt#225]
Not really a bug, but the README shows 3.14.6 whereas the release tag is 3.4.6.

HACS did not prompt me to upgrade to 3.4.6 from 3.14.5 but I could upgrade manually if I selected the 3.4.6 version, presumably because 4 < 14.

Thanks again for this project!

**Comment by fboundy** [comment]
Thanks for this - updated now to 3.14.7
