### ISSUE TITLE
Battery doesn't get charged in cheap periods

### ISSUE THREAD

**Issue by SzosszeNET** [stevebuk1/pv_opt#228]
In the past couple days noticed that the battery doesn't get charged as much as I would expect and not sure if PV operates with the most efficient cost.
My battery is almost empty have some cheap period followed by more expensive period but there is no charge scheduled

<img width="1421" alt="image" src="https://github.com/fboundy/pv_opt/assets/32844005/8b76484e-4050-4a6a-b5d0-c618944a6ee6">
<img width="1407" alt="image" src="https://github.com/fboundy/pv_opt/assets/32844005/3e8fa930-c0d5-4fb9-87a1-ad750b0ed6f2">
[error.log](https://github.com/fboundy/pv_opt/files/15434711/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/15434714/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/15434715/pv_opt.log)

**Comment by SzosszeNET** [comment]
main.log
pv_opt.log
error.log

**Comment by fboundy** [comment]
Since the weather got better I’ve noticed a problem with the optimiser which I think I’ve just got to the bottom of and should get fixed this weekend. Not sure if your issue is related but will try to have a look at the same time.

**Comment by fboundy** [comment]
> [error.log](https://github.com/fboundy/pv_opt/files/15434711/error.log) [main.log](https://github.com/fboundy/pv_opt/files/15434714/main.log) [pv_opt.log](https://github.com/fboundy/pv_opt/files/15434715/pv_opt.log)

I can't see these logs for some reason. Could you please re-upload? Thanks

**Comment by SzosszeNET** [comment]
[main.log](https://github.com/fboundy/pv_opt/files/15446799/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/15446800/pv_opt.log)
[error.log](https://github.com/fboundy/pv_opt/files/15446801/error.log)

Odd, just downloaded and re-uploaded them.

Since updated to 3.14.9 and indeed that seems have addressed it to some extent

**Comment by solarjones** [comment]
Seeing similar too, but also a [closed issue resurfaced in](https://github.com/fboundy/pv_opt/issues/227) 3.14.9 (I've added logs).
Thanks.

**Comment by solarjones** [comment]
[error.log](https://github.com/fboundy/pv_opt/files/15448186/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/15448187/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/15448188/pv_opt.log)

My battery is predicted to be flat at 23:00 and OE tariff showing cheaper slots before 05:00 when the price then ramps up. Notice it isn't showing the optimised blue trace line.

<img width="1716" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/e23bfd17-9d10-433a-b9c0-b7008357efbe">

**Comment by fboundy** [comment]
Try changing the “pass threshold” to zero

**Comment by solarjones** [comment]
> Try changing the “pass threshold” to zero
> 
> On 26 May 2024 at 17:22 +0100, solarjones ***@***.***>, wrote:
> 
> > error.log
> 
> > main.log
> 
> > pv_opt.log
> 
> > My battery is predicted to be flat at 23:00 and OE tariff showing cheaper slots before 05:00 when the price then ramps up. Notice it isn't showing the optimised blue trace line.
> 
> > image.png (view on web)
> 
> > —
> 
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > You are receiving this because you commented.Message ID: ***@***.***>
> 
> 

Unsure which parameter that is as I don't have that?

**Comment by SzosszeNET** [comment]
@solarjones it's the "charge threshold" in the bottom of the dashboard. By default it's 4

**Comment by fboundy** [comment]
Its called "Charge Threshold" on the dashboard

**Comment by solarjones** [comment]
> @solarjones it's the "charge threshold" in the bottom of the dashboard. By default it's 4

Thanks! Obvious now you said it 😀

**Comment by SzosszeNET** [comment]
Still something off. Not sure why the 15:30 slot doesn't trigger a charge and why only discharge is scheduled :/

<img width="1417" alt="image" src="https://github.com/fboundy/pv_opt/assets/32844005/f67de4ca-8b01-4239-ad9c-bf0bf2e81155">

<img width="958" alt="image" src="https://github.com/fboundy/pv_opt/assets/32844005/fded42e2-156f-4855-875a-149c0f2345eb">

**Comment by SzosszeNET** [comment]
[error.log](https://github.com/fboundy/pv_opt/files/15457105/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/15457108/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/15457111/pv_opt.log)
[pv_opt.log.patch](https://github.com/fboundy/pv_opt/files/15457120/pv_opt.log.patch)

**Comment by punkymuzzle** [comment]
Yep I'm having the same problem with my setup as well.
Recently there seems to be very few charging slots allocated, despite there being a large difference in unit price between now (for example) and my peak period of 16:00 - 19:00.
I adjusted the "Charge Threshold" to 0 as noted above, and it seemed to have started working again.  However, it's had another recalculation and again has totally ignored my cheapest slot.
I've ended up putting it in read only and manually setting my charging slots so I can at least get through the peak times later, but there seems to be something fundamentally wring with the calculations as it's missing key (relatively) cheap slots to charge.
My screenshot FYI:
![image](https://github.com/fboundy/pv_opt/assets/10165751/cff480a4-397c-45ca-bc02-dd00fa0753cc)

**Comment by fboundy** [comment]
It’s ignoring the cheap slots because they aren’t cheap enough to save you any money. The SOC shows your solar getting you to after the peak slots.

**Comment by punkymuzzle** [comment]
But at a basic level, it should be charging the battery at 14.51p, 15.54p etc, ready for discharging at the expensive times, which are approx twice the price? It didn't do this, which was why I had to put it in read only and manually charge, ready for peak slots.

> It’s ignoring the cheap slots because they aren’t cheap enough to save you any money. The SOC shows your solar getting you to after the peak slots.

But after the peak slots it's still more expensive than before, so why wouldn't it charge up as cheap as possible to last as far as possible overnight?

So roughly what does the difference in price between charging and discharging need to be before it considers it enough to set a charge?  From the above I have a 14 / 15p rate before peak, with approx. 30p peak - I would have thought that would have been plenty of difference?

**Comment by fboundy** [comment]
Sorry but I don’t see what you’re seeing. Battery isn’t forecast to be empty till midnight and you don’t have actual prices that far out. You’ve also got to factor in the round trip loss of charging and discharging the battery which is about 85% so a direct price of 16.5p is still cheaper than a battery charge price of 14p.

The whole point of the app is that it only charges the battery when it saves you money to do so. The detailed calculations are all in the log file and to some extent you can tune these with the tuning parameters. If you just want to charge it when the price is below a particular threshold there are much simpler approaches.
