### ISSUE TITLE
Unexpected error in worker for App pv_opt: + ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#233]
3.14.9

  File "/homeassistant/appdaemon/apps/pv_opt/pvpy.py", line 1020, in optimised_force
    self.flows(initial_soc, static_flows, slots=slots, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pvpy.py", line 528, in flows
    timed_slot_flows.loc[t] += int(c)
                               ^^^^^^
ValueError: cannot convert float NaN to integer

[error.log](https://github.com/fboundy/pv_opt/files/15459377/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/15459378/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/15459379/pv_opt.log)
[pv_opt.log.2.log](https://github.com/fboundy/pv_opt/files/15459380/pv_opt.log.2.log)

**Comment by fboundy** [comment]
Should be fixed in 3.14.10
