### ISSUE TITLE
solcast integration gone

### ISSUE THREAD

**Issue by SzosszeNET** [stevebuk1/pv_opt#234]
Not sure if you have seen but looks like ozie's solcast integration is gone, suspect following the issue earlier this week when the solcast integration was returning 429 responses...
So far haven't seen an alternative but the old project...
Just FYI

**Comment by fboundy** [comment]
Ah, ok - that’s a bit of a pain.

**Comment by fboundy** [comment]
Try this:

**Comment by fboundy** [comment]
Try this: https://github.com/BJReplay/ha-solcast-solar

**Comment by SzosszeNET** [comment]
Thank you, I'll check it out

**Comment by swests** [comment]
Confirmed that using the BJReplay fork for solcast works.  Just remove the old one from HACS, add the BJReplay repo as per the readme, install and restart.
