### ISSUE TITLE
Set up help

### ISSUE THREAD

**Issue by Gorwanvfr** [stevebuk1/pv_opt#235]
Looking for some help please.
I have gone so far with the install but have reached the end of my knowledge. I know I'm doing something wrong but have no idea what. I was having issues getting the mqtt broker to work but I finally figure out my mistake and I think it is working now. When I start AppDaemon it runs and creates the different log files. The issue is I can not see any of the entities within home assistant  
![image](https://github.com/fboundy/pv_opt/assets/132362732/a59b1446-5a32-4428-a807-a9f17fd3dded).
Thanks in advance [
[Pv_opt_log.txt](https://github.com/user-attachments/files/15522409/Pv_opt_log.txt)
[Main_Log.txt](https://github.com/user-attachments/files/15522410/Main_Log.txt)
[Error_log.txt](https://github.com/user-attachments/files/15522411/Error_log.txt)
](url)

**Comment by fboundy** [comment]
Can you please also share what you have in your `config.yaml` file?

**Comment by Gorwanvfr** [comment]
HI @fboundy 
            Please find attached the config file


[config.yaml.txt](https://github.com/user-attachments/files/15531172/config.yaml.txt)

**Comment by stevebuk1** [comment]
Hi @Gorwanvfr , did you manage to get up and running ok?
