### ISSUE TITLE
Unexpected error in worker for App pv_opt:: AttributeError: 'numpy.float64' object has no attribute 'interpolate'

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#240]
v3.15.0
Hit another error:

[error.log](https://github.com/user-attachments/files/15739279/error.log)

Thanks

**Comment by Bart39** [comment]
Same issue as #243 maybe ?

**Comment by fboundy** [comment]
I'm assuming this is stale? The object in this line should be a DataFrame not a numpy.64 object
