### ISSUE TITLE
PV-OPT stopped working after update to 3.15.2 

### ISSUE THREAD

**Issue by punkymuzzle** [stevebuk1/pv_opt#244]
**Describe the bug**
upgraded pv_opt to version 3.15.2 and all seemed to work well initially.
However, the Dashboard no longer works and it seems like there are entities missing.  
Looking at the logs it appears to be trying to load the solis config, but my inverter is SOLAX.  So need to understand how to tell pv_opt to load the solax config

Logs attached also
Screenshot attached below:

**To Reproduce**
upgrade to 3.15.2

**Expected behaviour**
Dashboard shows correctly in HA

**Screenshots**
![image](https://github.com/fboundy/pv_opt/assets/10165751/e62e9010-fe5e-43e6-86af-b75931d98fe7)
![image](https://github.com/fboundy/pv_opt/assets/10165751/28efca10-4598-4fba-a3a6-d39c12146256)

**Desktop (please complete the following information):**
 - OS: RaspPi running HA

**Smartphone (please complete the following information):**
N/A

**Additional context**
[error.log](https://github.com/user-attachments/files/15906129/error.log)
[pv_opt.log](https://github.com/user-attachments/files/15906130/pv_opt.log)

**Comment by fboundy** [comment]
Do you read the release notes about the changes to the AppDaemon config?

**Comment by punkymuzzle** [comment]
I saw there was an update and there was some mention of one of the repositories changing version?
Is there an easy way to load and re-read the release notes?  Assuming I need to do something in AppDaemon to reconfigure it?
Just seen in the instructions to add this in the AppDaemon config:

>   - pandas
>  - numpy==1.26.4

So will give that a go.

Thanks

**Comment by punkymuzzle** [comment]
Yep that worked, thanks very much for the pointer.

**Comment by fboundy** [comment]
https://github.com/fboundy/pv_opt/releases/tag/3.15.2

**Comment by punkymuzzle** [comment]
All working now, thank you very much for the help
