### ISSUE TITLE
pv_opt crashing after hours of use

### ISSUE THREAD

**Issue by punkymuzzle** [stevebuk1/pv_opt#257]
**Describe the bug**
Everything works fine, then (usually in the morning) pv_opt seems to stop working.  AppDaemon reports errors.
Inverter settings (usually self use mode with a time of 00:00) seem to stick to a previous time.

Seems to work again after AppDaemon restart

**To Reproduce**
I just leave pv_opt running overnight.

**Screenshots**
AppDaemon Log:

 * 09:55:42 timestamp was from yesterday morning.
![image](https://github.com/user-attachments/assets/05ee3287-d004-4501-965c-058738e37bd8)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Logs attached:

[pv_opt.log](https://github.com/user-attachments/files/16452661/pv_opt.log)
[main.log](https://github.com/user-attachments/files/16452662/main.log)
[error.log](https://github.com/user-attachments/files/16452663/error.log)

**Comment by fboundy** [comment]
Looks like it is because the battery voltage is reading zero. I've added a default of 100 in the latest patch.

**Comment by punkymuzzle** [comment]
Awesome, thank you
