### ISSUE TITLE
AppDaemon Log showing lots of : FutureWarning: The behavior of array concatenation with empty entries is deprecated

### ISSUE THREAD

**Issue by swests** [stevebuk1/pv_opt#261]
**Describe the bug**
AppDaemon Log showing lots of : "FutureWarning: The behavior of array concatenation with empty entries is deprecated" warnings

HA: 2024.7.4
PV_Opt: 3.15.4

**To Reproduce**
1. Start AppDaemon
2. Goto the the AppDaemon log

**Expected behavior**
No errors/warnings

**Screenshots**
From  AppDaemon Log:
```
/homeassistant/appdaemon/apps/pv_opt/pv_opt.py:2175: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  cost = pd.DataFrame(pd.concat([cost_today, cost])).set_axis(["cost"], axis=1).fillna(0)
```

**Additional context**
It's a warning for now, but one for the backlog?

**Comment by fboundy** [comment]
Yes - should be an easy enough thing to fix.
