### ISSUE TITLE
Not using cheapest slots for import

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#271]
I can't work out why, perhaps I've got a setting wrong somewhere?

PV Opt v3.15.5

Would you expect the import to be from 02:30-05:00 and then hold at 100%? Can't understand why it wants to complete the charge in the more expensive slots.
<img width="431" alt="image" src="https://github.com/user-attachments/assets/5f9d071d-6d82-4fe4-bfad-3ca55a7f413b">

<img width="415" alt="image" src="https://github.com/user-attachments/assets/df98d429-8216-4d13-bc2b-22b6a4209a44">

[main.log](https://github.com/user-attachments/files/17197378/main.log)
[pv_opt.log](https://github.com/user-attachments/files/17197379/pv_opt.log)

Thanks in advance,

**Comment by fboundy** [comment]
I think the optimisation is fine. The slots being used are from 02:30 to 04:30 which are the cheapest. For some reason the summary is reporting charging till 06:00 but that's not what the detail says.

    00:13:39     INFO: >>> Slot: 01/10 02:30 UTC Factor: 1.000 Forced:      0W  End SOC: 15.0%  SPR:   3671W  SCPA:   6000W  SAC:  16320W  Min Power:   3671W
    00:13:39     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 03:30 BST:  2.30p/kWh  4.22p  SOC:  15.0%-> 15.0% New SOC:  15.0%-> 32.4% Net:  472.8
    00:13:39     INFO: >>> Slot: 01/10 02:30 UTC Factor: 1.000 Forced:   3671W  End SOC: 32.4%  SPR:   3671W  SCPA:   2329W  SAC:  12979W  Min Power:   2329W
    00:13:39     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 03:30 BST:  2.30p/kWh  4.22p  SOC:  15.0%-> 32.4% New SOC:  15.0%-> 43.4% Net:  463.7
    00:13:39     INFO: >>> Slot: 01/10 03:00 UTC Factor: 1.000 Forced:      0W  End SOC: 37.3%  SPR:   3671W  SCPA:   6000W  SAC:  12046W  Min Power:   3671W
    00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:00 BST:  3.71p/kWh  6.80p  SOC:  43.4%-> 37.3% New SOC:  43.4%-> 60.8% Net:  429.2
    00:13:40     INFO: >>> Slot: 01/10 03:00 UTC Factor: 1.000 Forced:   3671W  End SOC: 60.8%  SPR:   3671W  SCPA:   2329W  SAC:   7519W  Min Power:   2329W
    00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:00 BST:  3.71p/kWh  6.80p  SOC:  43.4%-> 60.8% New SOC:  43.4%-> 71.9% Net:  416.0
    00:13:40     INFO: >>> Slot: 01/10 03:30 UTC Factor: 1.000 Forced:      0W  End SOC: 64.7%  SPR:   3671W  SCPA:   6000W  SAC:   6771W  Min Power:   3671W
    00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:30 BST:  3.97p/kWh  7.28p  SOC:  71.9%-> 64.7% New SOC:  71.9%-> 89.3% Net:  344.4
    00:13:40     INFO: >>> Slot: 01/10 03:30 UTC Factor: 1.000 Forced:   3671W  End SOC: 89.3%  SPR:   3671W  SCPA:   2329W  SAC:   2059W  Min Power:   2059W
    00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:30 BST:  3.97p/kWh  7.28p  SOC:  71.9%-> 89.3% New SOC:  71.9%-> 99.0% Net:  314.2
    00:13:40     INFO: >>> Slot: 01/10 04:00 UTC Factor: 1.000 Forced:      0W  End SOC: 90.9%  SPR:   3671W  SCPA:   6000W  SAC:   1743W  Min Power:   1743W
    00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 05:00 BST: 10.80p/kWh 19.83p  SOC:  99.0%-> 90.9% New SOC:  99.0%->100.0% Net:  290.6
    00:13:40     INFO: >>> Slot: 01/10 04:30 UTC Factor: 1.000 Forced:      0W  End SOC: 93.0%  SPR:   3671W  SCPA:   6000W  SAC:   1353W  Min Power:   1353W
    00:13:40     INFO: 01/10 19:00 BST:  1.84 kWh at  40.54p. <==> 01/10 05:30 BST: 11.77p/kWh 21.60p  SOC: 100.0%-> 93.0% New SOC: 100.0%->100.0% Net:  272.6

**Comment by solarjones** [comment]
Is the summary wrong? That’s all I look at to be honest. Sent from my iPhoneOn 12 Nov 2024, at 17:00, fboundy ***@***.***> wrote:﻿
I think the optimisation is fine. The slots being used are from 02:30 to 04:30 which are the cheapest. For some reason the summary is reporting charging till 06:00 but that's not what the detail says.
00:13:39     INFO: >>> Slot: 01/10 02:30 UTC Factor: 1.000 Forced:      0W  End SOC: 15.0%  SPR:   3671W  SCPA:   6000W  SAC:  16320W  Min Power:   3671W
00:13:39     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 03:30 BST:  2.30p/kWh  4.22p  SOC:  15.0%-> 15.0% New SOC:  15.0%-> 32.4% Net:  472.8
00:13:39     INFO: >>> Slot: 01/10 02:30 UTC Factor: 1.000 Forced:   3671W  End SOC: 32.4%  SPR:   3671W  SCPA:   2329W  SAC:  12979W  Min Power:   2329W
00:13:39     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 03:30 BST:  2.30p/kWh  4.22p  SOC:  15.0%-> 32.4% New SOC:  15.0%-> 43.4% Net:  463.7
00:13:39     INFO: >>> Slot: 01/10 03:00 UTC Factor: 1.000 Forced:      0W  End SOC: 37.3%  SPR:   3671W  SCPA:   6000W  SAC:  12046W  Min Power:   3671W
00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:00 BST:  3.71p/kWh  6.80p  SOC:  43.4%-> 37.3% New SOC:  43.4%-> 60.8% Net:  429.2
00:13:40     INFO: >>> Slot: 01/10 03:00 UTC Factor: 1.000 Forced:   3671W  End SOC: 60.8%  SPR:   3671W  SCPA:   2329W  SAC:   7519W  Min Power:   2329W
00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:00 BST:  3.71p/kWh  6.80p  SOC:  43.4%-> 60.8% New SOC:  43.4%-> 71.9% Net:  416.0
00:13:40     INFO: >>> Slot: 01/10 03:30 UTC Factor: 1.000 Forced:      0W  End SOC: 64.7%  SPR:   3671W  SCPA:   6000W  SAC:   6771W  Min Power:   3671W
00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:30 BST:  3.97p/kWh  7.28p  SOC:  71.9%-> 64.7% New SOC:  71.9%-> 89.3% Net:  344.4
00:13:40     INFO: >>> Slot: 01/10 03:30 UTC Factor: 1.000 Forced:   3671W  End SOC: 89.3%  SPR:   3671W  SCPA:   2329W  SAC:   2059W  Min Power:   2059W
00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 04:30 BST:  3.97p/kWh  7.28p  SOC:  71.9%-> 89.3% New SOC:  71.9%-> 99.0% Net:  314.2
00:13:40     INFO: >>> Slot: 01/10 04:00 UTC Factor: 1.000 Forced:      0W  End SOC: 90.9%  SPR:   3671W  SCPA:   6000W  SAC:   1743W  Min Power:   1743W
00:13:40     INFO: 01/10 18:30 BST:  1.84 kWh at  63.44p. <==> 01/10 05:00 BST: 10.80p/kWh 19.83p  SOC:  99.0%-> 90.9% New SOC:  99.0%->100.0% Net:  290.6
00:13:40     INFO: >>> Slot: 01/10 04:30 UTC Factor: 1.000 Forced:      0W  End SOC: 93.0%  SPR:   3671W  SCPA:   6000W  SAC:   1353W  Min Power:   1353W
00:13:40     INFO: 01/10 19:00 BST:  1.84 kWh at  40.54p. <==> 01/10 05:30 BST: 11.77p/kWh 21.60p  SOC: 100.0%-> 93.0% New SOC: 100.0%->100.0% Net:  272.6
