### ISSUE TITLE
Is there a walk through guide for configuration of AppDaemon ?

### ISSUE THREAD

**Issue by rosenightingale** [stevebuk1/pv_opt#319]
Hi, I'm trying to add this integration to HA in order to get my Solis inverter to charge batteries during Intelligent Octopus Go cheap slots which appear outside of the 11.30am to 5.30am fixed overnight period. 
Working through the installation, I have got stuck with configuring the AppDaemon. I'm not a developer or coder, so would appreciate a step by step guide to this please. I have opened File Editor on HA, but can't see the next step of where to do the configuration. Are there some instructions I can follow for this, please? 
Also, I downloaded and added an integration for Solcast today, it's showing a failed set up, so perhaps this is just waiting for the information to come online, but if I have done something wrong here, would appreciate knowing how to fix it. Many thanks. 
![image](https://github.com/user-attachments/assets/7c59fefa-7bf1-4b01-bf06-aa5a3ca1fa70)

**Comment by stevebuk1** [comment]
Re Solcast, have you visited www.solcast.com and setup a "Home User" account with details of your solar array (power, inclination and direction). The Solcast integration will use the solcast website to get a solar forecast for your setup at your exact location. 
The above is this bit in the Pv_opt setup guide:

![image](https://github.com/user-attachments/assets/b212ad60-d8f1-437e-8aeb-162cee8aba95)

From your Facebook post I remember you got stuck with locating /addon_configs so you could configure appdaemon?

![image](https://github.com/user-attachments/assets/bcb29b5e-f147-48dd-b4eb-abe3d76fa8ad)

This is most probably because theres a setting in file editor that you need to change so you can access the root directory. In HomeAssistant, go to Settings -> AddOns -> File Editor then click on the Configuration tab. The following image should display. 
Toggle "Force BasePath" to Off, like mine, then press Save at the bottom right:

![image](https://github.com/user-attachments/assets/96fe00ee-cc23-4f0e-aeac-ae92c4c6c614)

That should allow you to find addon_configs.

**Comment by rosenightingale** [comment]
Many thanks, yes I have set up the Solcast Hobby account and inputted my API, that was all fine.  I'm still getting the 'Failed Setup, Will retry' message, but will check again tomorrow in case that's cleared. 
Thank you for the information on changing the setup in the file editor. I did that, and can now see the following screen.  Sorry for the basic question, but do I now just copy and paste the configuration code into this white box? I can't see how to search for anything, does it look correct please? 
![image](https://github.com/user-attachments/assets/be31150d-81e5-4067-9789-889a619c805b)

**Comment by stevebuk1** [comment]
> Many thanks, yes I have set up the Solcast Hobby account and inputted my API, that was all fine. I'm still getting the 'Failed Setup, Will retry' message, but will check again tomorrow in case that's cleared. 

Ok, not sure of that, I still use the original Solcast integration (the one that is now deleted from HACS), lets see if it is an issue tomorrrow. 

> Thank you for the information on changing the setup in the file editor. I did that, and can now see the following screen. Sorry for the basic question, but do I now just copy and paste the configuration code into this white box? I can't see how to search for anything, does it look correct please? 

So this is a file editor, like notepad in windows. The file we need to edit (`/addon_configs/a0d7b954_appdaemon/appdaemon.yaml`) already exists, so we need to navigate to its location and open it. 

Click the folder icon (leftmost icon in the blue bar at the top. Then click the left arrow until you get all the way to root, signified by a /, as below:

![image](https://github.com/user-attachments/assets/c9b3e732-4e65-41d7-aa6b-8931679bd340)

You'll see the folder addon_configs, click on it, then on a0d7b954_appdaemon, then on appdaemon.yaml (the file you want to edit), and it should then open:

![image](https://github.com/user-attachments/assets/9fd02b7f-ea78-462c-944e-8c44faae835d)

Click anywhere on the right hand side, and you can now edit the file:

![image](https://github.com/user-attachments/assets/0557175e-6031-4aff-8d92-1b3a012591b8)

To save, its the floppy disc icon, top right (it will be red if there are edits to save)

**Comment by rosenightingale** [comment]
That is incredibly helpful. I think I've now achieved this, copying across the code, my file editor now looks like this.  Hopefully ok. I think the next step on the list is secrets yaml (?) and onwards from there. Thank you for bearing with me!
![image](https://github.com/user-attachments/assets/c77228e7-6fcc-41fd-9635-a8c4a48f23c3)

**Comment by stevebuk1** [comment]
If you don't have a secrets.yaml already, to save time you could insert your MQTT username and password in this file directly (as I did in mine, see my screenshot). 

Then carry on working down the instructions.

**Comment by rosenightingale** [comment]
Many thanks. It looks like I don't have a username and password for mqqt yet either, so although it's installed it's not configured. Will try to read up how to do that. In the meantime, still no luck connecting to the solcast unfortunately, despite installing and inserting API.
![image](https://github.com/user-attachments/assets/152e1dc4-09bf-4c89-b2b2-582c6962f9e6)

**Comment by stevebuk1** [comment]
Hi Rose, where did you get to with this? Is it all working now or did you go another route?

**Comment by rosenightingale** [comment]
Thanks for asking Steve, I really couldn't get this to work, unfortunately. The Solcast doesn't install properly although tried it several times. I've actually found another solution which is working well, using Solis Modbus and the times now change in line with the octopus dispatches, so very pleased that it's automated. Hopefully the solcast installation process can be sorted however, if others want to use it.

**Comment by stevebuk1** [comment]
Thanks for letting me know and sorry you couldn't get Solcast working. Good you've got something up and running using the Octopus integration.
