### ISSUE TITLE
Battery not charging / discharging 

### ISSUE THREAD

**Issue by lazy-pete** [stevebuk1/pv_opt#330]
**Describe the bug**

Hi - since 21/12 my battery doesn’t seem to have been charging / discharging. PV-Opt has been so solid lately I’d stopped my daily checks routine over the holidays. I’m not sure if it’s a PV-Opt thing or an inverter battery thing, so have opened a solid ticket as well (and reconnected to the Solis cloud for that purpose). 

It seems as if on the 22nd it just stopped working and is getting whatever PV charge happened that day but not discharging on demand to the house. Similarly, it doesn’t seem to have had received any programmed top ups from PV-Opt. 

I’m a bit confused. 

![IMG_8882](https://github.com/user-attachments/assets/62453da4-ea46-48a6-b4c1-5846a6b4cb37)
[error.log](https://github.com/user-attachments/files/18274707/error.log)
[main.log](https://github.com/user-attachments/files/18274708/main.log)
[pv_opt.log](https://github.com/user-attachments/files/18274709/pv_opt.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lazy-pete** [comment]
Never mind - had a grid connection fault on the inverter, and it seems the main breaker to the house had tripped, presumably on the 21st. Shall have to set up an automation to alert me to that happening somehow.

**Comment by stevebuk1** [comment]
Pleased you found the issue although hopefully the breaker trip was a one off! 

An HA automation is a good way. Or, to keep an eye on things I use an an old mobile phone pinned to the kitchen wall with the HomeAsssistant mobile app permanently displayed - with a few gauges on battery SOC, grid current (using a Shelly EM) and Solar power from the inverter, tends to let me know if everythings ok or somethings crashed/not working.

**Comment by lazy-pete** [comment]
Good idea - thanks !
