### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#71]
Hello, if you are able to provide some assistance, that would be very much appriciated. This isn't a bug I don't think, but the pvopt_dashboard.yaml has some errors for me, of which it reports these are not available:
sensor.solis_grid_import_power
sensor.solis_grid_export_power

How have you defined these? I don't seem to have them. 

I'm connecting to my Solis inverter using a S2-WL-ST via:
[alienatedsec](https://github.com/alienatedsec) RS485 to TCP 
[homeassistant-solax-modbus](https://github.com/wills106/homeassistant-solax-modbus)

Solax-Modbus is working fine and I manually update the charging times currently. I was on Octopus Eco7 but recently switched to Agile. 

Thanks.

**Comment by fboundy** [comment]
Added the necessary template sensors to the readmin in 3.4.1

**Comment by solarjones** [comment]
Thanks I've added those now.

**Comment by lazy-pete** [comment]
Hi - I was also missing those. I've copied / pasted them into yaml, then moved them around / added quotation marks etc so the yaml saves successfully, but no foy in dashboard. Looks like the entity names are ok, but not finding them either in dashboard or entities list.

![Screenshot 2024-01-12 02 24 54](https://github.com/fboundy/pv_opt/assets/30950467/a60674e8-fadf-4fa5-86dd-6c50be78bc81)
![Screenshot 2024-01-12 02 23 15](https://github.com/fboundy/pv_opt/assets/30950467/901a15e4-b895-4f37-a483-0237243e518c)
