### ISSUE TITLE
AppDaemon Install Issue

### ISSUE THREAD

**Issue by TikTok90** [stevebuk1/pv_opt#86]
In section 10. Install AppDaemon, para 1. the button to click to install doesn't seem to be visible to me. I've also tried finding AppDaemon in HACS and can't seem to find it there either.

![image](https://github.com/fboundy/pv_opt/assets/138300803/e6772a2b-4fec-4bcd-bd21-b9db958b5666)

The MQTT button is present though

![image](https://github.com/fboundy/pv_opt/assets/138300803/70302c6f-3d1b-4d79-adb8-5d04db2fb3f5)

**Desktop (please complete the following information):**
 - Windows
 - Opera One
 - Version 106.0.4998.19)

**Comment by fboundy** [comment]
Go to Settings / Add-Ons. You should find it there

**Comment by TikTok90** [comment]
Got it - thanks
